{"name": "Проверка невозможности авторизоваться с несуществующим логином. Получаем ошибку 404", "status": "passed", "steps": [{"name": "Логинимся курьером", "status": "passed", "parameters": [{"name": "login", "value": "'snehpiivcz'"}, {"name": "password", "value": "'snehpiivcz'"}], "start": 1719232035374, "stop": 1719232035451}], "start": 1719232035373, "stop": 1719232035453, "uuid": "e83b23fd-5277-4edd-8be5-1db37b926be8", "historyId": "723b12d322f96c5e4f09f64205b327f0", "testCaseId": "723b12d322f96c5e4f09f64205b327f0", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_with_incorrect_login", "labels": [{"name": "story", "value": "Тесты на вход курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-7KB2K2E"}, {"name": "thread", "value": "15328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}